// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJsjpsQr-IVIOtAyqx8i8RFqRhtDHd8W4',
    appId: '1:83107759419:web:c0c774c16fb0da1e6ea31e',
    messagingSenderId: '83107759419',
    projectId: 'masarak-app',
    authDomain: 'masarak-app.firebaseapp.com',
    storageBucket: 'masarak-app.firebasestorage.app',
    measurementId: 'G-2RMRHHFCPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaadxcHNYN5Ca_vwNNPa2Qv1ltiUAc9II',
    appId: '1:83107759419:android:222f8b03c2bc09796ea31e',
    messagingSenderId: '83107759419',
    projectId: 'masarak-app',
    storageBucket: 'masarak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYw5p1v77SgKqyklzMF7eJKGiVQsJpi5s',
    appId: '1:83107759419:ios:cd9885e9d40b50c16ea31e',
    messagingSenderId: '83107759419',
    projectId: 'masarak-app',
    storageBucket: 'masarak-app.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYw5p1v77SgKqyklzMF7eJKGiVQsJpi5s',
    appId: '1:83107759419:ios:cd9885e9d40b50c16ea31e',
    messagingSenderId: '83107759419',
    projectId: 'masarak-app',
    storageBucket: 'masarak-app.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJsjpsQr-IVIOtAyqx8i8RFqRhtDHd8W4',
    appId: '1:83107759419:web:68535cbf2b9aa51d6ea31e',
    messagingSenderId: '83107759419',
    projectId: 'masarak-app',
    authDomain: 'masarak-app.firebaseapp.com',
    storageBucket: 'masarak-app.firebasestorage.app',
    measurementId: 'G-WEP7NBMQFD',
  );
}
